server:
  port: 8082
  servlet:
    session:
      timeout: 30m
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false #热部署静态文件，禁止缓存
    mode: HTML5 #使用HTML5标准
#配置数据源
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://136.192.50.29:23306/scwvg?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/scwvg?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver # com.mysql.cj.jdbc.Driver #
    ################### druid 数据库连接池配置 ###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始连接池大小
    dbcp2:
      initial-size: 2
      min-idle: 5
      max-idle: 20
      # 配置获取连接等待超时的时间
      max-wait-millis: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  jpa:
    hibernate:
      ddl-auto: update #自动更新建表
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect # 配置數據庫方言
  #配置国际化校验的properties文件
  messages:
    basename: i18n/validation/ValidationMessages
  #springboot之json中日期格式转换问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 配置驼峰属性自动映射
  mapper-locations: classpath:com/scwvg/system/mapper/*.xml  # 指定sql映射文件的位置
# mybatis 分页插件
pagehelper:
    helperDialect: mysql          # 定义分页插件检测的数据库链接
    offsetAsPageNum: true         # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效.设置为 true 将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页
    rowBoundsWithCount: true      # 默认值为false，该参数对使用 RowBounds 作为分页参数时有效。设置为 true 使用 RowBounds 分页会进行 count 查询
    supportMethodsArguments: true # 启用支持通过 Mapper 接口参数来传递分页参数，默认值false
    params: pageNum=pageNum;pageSize=pageSize;count=countSql          # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
