server:
  port: 8086
##########################mybatis数据源配置Start###########################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scwvg.entitys.scwvgponnetwork
spring:
  thymeleaf:
    cache: false   #是否开启缓存
    mode: LEGACYHTML5
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://136.192.50.29:23306/scwvg?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: root
      password: lul@123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT ‘x’
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
##########################mybatis数据源配置end###########################
######################jpa数据源#########################
  #jpa:
    #database: mysql
    #show-sql: true
######################jpa数据源end#########################
