# mybatis 的配置信息
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 配置驼峰属性自动映射
  mapper-locations:
  - classpath:com/scwvg/zgy/system/mapper/*.xml  # 指定sql映射文件的位置
  - classpath:com/scwvg/zgy/commons/thymeleaf/dataset/mapper/*.xml  # 指定sql映射文件的位置
# mybatis 分页插件
pagehelper:
    helperDialect: mysql          # 定义分页插件检测的数据库链接
    offsetAsPageNum: true         # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效.设置为 true 将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页
    rowBoundsWithCount: true      # 默认值为false，该参数对使用 RowBounds 作为分页参数时有效。设置为 true 使用 RowBounds 分页会进行 count 查询
    supportMethodsArguments: true # 启用支持通过 Mapper 接口参数来传递分页参数，默认值false
    params: pageNum=pageNum;pageSize=pageSize;count=countSql          # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
